In [22]:
import torch
import torch.nn as nn
import tensorflow as tf
from torch.nn.parameter import Parameter


2022-12-14 09:08:12.908153: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-14 09:08:12.996677: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-12-14 09:08:13.309312: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-14 09:08:13.309515: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not l

In [2]:
z_dim = 64 # size of hidden network
f_size = 3 #f x f = size of filter
out_size = 16 #n out
in_size = 16 # n in

In [8]:
torch.fmod(torch.randn((z_dim, out_size*f_size*f_size)),2).shape

torch.Size([64, 144])

In [9]:
torch.fmod(torch.randn((z_dim, out_size*f_size*f_size)),2)

tensor([[ 0.0703, -1.4856,  0.2479,  ..., -0.3749,  0.4192, -1.4081],
        [-0.2227, -1.0392, -0.3760,  ...,  0.7645, -0.6861,  1.7092],
        [-0.1460,  0.0468,  0.0946,  ..., -0.8690,  1.1771, -0.7853],
        ...,
        [ 0.1372, -0.0980, -0.5430,  ..., -1.3790,  0.3250, -0.3281],
        [-1.2242,  0.8323, -0.5148,  ...,  1.3558,  0.1761,  0.0818],
        [ 0.1265,  0.4691,  1.7454,  ...,  0.3715,  0.3600, -1.0550]])

In [13]:
w2 = Parameter(torch.fmod(torch.randn((z_dim, in_size*z_dim)),2))
w2

Parameter containing:
tensor([[-0.7387,  0.2444, -0.7003,  ...,  0.3713,  1.7027, -0.8824],
        [ 0.2957, -0.3498,  0.0460,  ...,  0.3695,  0.3559, -0.5695],
        [ 0.7016,  0.5133,  0.0989,  ..., -0.8251, -1.9940, -0.7673],
        ...,
        [-0.1161, -0.1865,  0.8399,  ...,  0.8793,  1.3347, -0.2941],
        [ 0.0791, -0.3437,  0.9107,  ..., -0.7575, -0.7236,  1.0921],
        [-0.0144, -0.1513,  1.3502,  ...,  0.6208, -0.5305, -0.7822]],
       requires_grad=True)

In [16]:
w2.shape

torch.Size([64, 1024])

In [14]:
b2 = Parameter(torch.fmod(torch.randn((in_size*z_dim)),2))
b2

Parameter containing:
tensor([-0.5481, -0.4595,  0.2472,  ..., -0.5857,  0.4291,  0.3004],
       requires_grad=True)

In [18]:
b2.view(in_size,z_dim)

tensor([[-0.5481, -0.4595,  0.2472,  ..., -0.4045, -0.1659, -1.0828],
        [ 0.6983,  0.2274,  0.3918,  ..., -1.7585, -1.1770,  0.6894],
        [-0.3160, -0.8322, -1.7753,  ...,  0.6724,  0.0499,  0.4677],
        ...,
        [ 1.0175,  0.2681,  0.0362,  ...,  0.8128, -0.6224,  1.3235],
        [-1.1136,  1.1548, -0.3572,  ..., -1.2950, -1.5725, -0.0117],
        [-1.3484,  0.1052,  0.0677,  ..., -0.5857,  0.4291,  0.3004]],
       grad_fn=<ViewBackward0>)

In [19]:
b2.shape

torch.Size([1024])

In [20]:
b2.view(in_size,z_dim).shape

torch.Size([16, 64])

In [28]:
user_input =  tf.keras.Input(shape=(1,), dtype = tf.int32)
user_input

<KerasTensor: shape=(None, 1) dtype=int32 (created by layer 'input_3')>

In [31]:
W = nn.Parameter(torch.empty(1000, 10))

torch.rand(W.size())

tensor([[0.0239, 0.8258, 0.3827,  ..., 0.1090, 0.7409, 0.5875],
        [0.2535, 0.4195, 0.6921,  ..., 0.3314, 0.6141, 0.4942],
        [0.7242, 0.0044, 0.7544,  ..., 0.1495, 0.4691, 0.4868],
        ...,
        [0.2914, 0.7402, 0.6242,  ..., 0.2302, 0.9247, 0.3229],
        [0.0643, 0.5509, 0.5987,  ..., 0.5462, 0.0895, 0.3603],
        [0.8078, 0.7529, 0.7934,  ..., 0.0743, 0.8873, 0.8552]])

In [32]:
W

Parameter containing:
tensor([[ 1.4013e-45,  0.0000e+00,  1.4046e+10,  ...,  3.0638e-41,
          3.3631e-44,  0.0000e+00],
        [ 7.4209e+28,  4.5604e-41,  2.8026e-45,  ...,  0.0000e+00,
          1.4013e-45,  1.4013e-45],
        [ 3.3631e-44,  0.0000e+00,  1.6298e+28,  ...,  0.0000e+00,
          1.4013e-45,  5.6052e-45],
        ...,
        [ 3.5641e-24, -2.1221e-32,  1.6602e+28,  ...,  5.9052e+28,
          1.7372e+28,  4.5604e-41],
        [ 1.6775e+28,  4.5604e-41, -5.3256e+15,  ...,  4.5604e-41,
          3.6185e+36, -5.8465e+05],
        [ 1.6602e+28,  4.5604e-41,  1.6262e+28,  ...,  4.5604e-41,
          1.6440e+28,  4.5604e-41]], requires_grad=True)

In [36]:
model = torch.load('/home/vuhoang181/Documents/code_base/APR-PyTorch/output/bpr.pt')
model

OrderedDict([('W',
              tensor([[ 0.1688, -0.2413,  0.2419,  ..., -0.4401,  0.1959, -0.1697],
                      [-0.1532,  0.0245, -0.2731,  ..., -0.1908,  0.3244,  0.4377],
                      [ 0.3093, -0.1605, -0.3160,  ..., -0.3087,  0.3495,  0.2956],
                      ...,
                      [ 0.2222, -0.3336,  0.2879,  ..., -0.2875,  0.0850, -0.0670],
                      [ 0.3501, -0.2677,  0.2439,  ..., -0.3854, -0.0697,  0.0715],
                      [-0.1991,  0.2569, -0.2841,  ..., -0.0532,  0.3571, -0.0187]])),
             ('H',
              tensor([[-0.2028, -0.0171, -0.2878,  ..., -0.3116, -0.3321, -0.1965],
                      [-0.2699,  0.2468, -0.3852,  ..., -0.3054, -0.3241, -0.3902],
                      [-0.2920,  0.3309, -0.4028,  ..., -0.3486, -0.2032, -0.3428],
                      ...,
                      [-0.3181,  0.0880,  0.1746,  ..., -0.0030, -0.3075, -0.2670],
                      [-0.0627,  0.2558, -0.2627,  ..., -0.2470, 