In [11]:
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter


In [2]:
z_dim = 64 # size of hidden network
f_size = 3 #f x f = size of filter
out_size = 16 #n out
in_size = 16 # n in

In [8]:
torch.fmod(torch.randn((z_dim, out_size*f_size*f_size)),2).shape

torch.Size([64, 144])

In [9]:
torch.fmod(torch.randn((z_dim, out_size*f_size*f_size)),2)

tensor([[ 0.0703, -1.4856,  0.2479,  ..., -0.3749,  0.4192, -1.4081],
        [-0.2227, -1.0392, -0.3760,  ...,  0.7645, -0.6861,  1.7092],
        [-0.1460,  0.0468,  0.0946,  ..., -0.8690,  1.1771, -0.7853],
        ...,
        [ 0.1372, -0.0980, -0.5430,  ..., -1.3790,  0.3250, -0.3281],
        [-1.2242,  0.8323, -0.5148,  ...,  1.3558,  0.1761,  0.0818],
        [ 0.1265,  0.4691,  1.7454,  ...,  0.3715,  0.3600, -1.0550]])

In [13]:
w2 = Parameter(torch.fmod(torch.randn((z_dim, in_size*z_dim)),2))
w2

Parameter containing:
tensor([[-0.7387,  0.2444, -0.7003,  ...,  0.3713,  1.7027, -0.8824],
        [ 0.2957, -0.3498,  0.0460,  ...,  0.3695,  0.3559, -0.5695],
        [ 0.7016,  0.5133,  0.0989,  ..., -0.8251, -1.9940, -0.7673],
        ...,
        [-0.1161, -0.1865,  0.8399,  ...,  0.8793,  1.3347, -0.2941],
        [ 0.0791, -0.3437,  0.9107,  ..., -0.7575, -0.7236,  1.0921],
        [-0.0144, -0.1513,  1.3502,  ...,  0.6208, -0.5305, -0.7822]],
       requires_grad=True)

In [16]:
w2.shape

torch.Size([64, 1024])

In [14]:
b2 = Parameter(torch.fmod(torch.randn((in_size*z_dim)),2))
b2

Parameter containing:
tensor([-0.5481, -0.4595,  0.2472,  ..., -0.5857,  0.4291,  0.3004],
       requires_grad=True)

In [18]:
b2.view(in_size,z_dim)

tensor([[-0.5481, -0.4595,  0.2472,  ..., -0.4045, -0.1659, -1.0828],
        [ 0.6983,  0.2274,  0.3918,  ..., -1.7585, -1.1770,  0.6894],
        [-0.3160, -0.8322, -1.7753,  ...,  0.6724,  0.0499,  0.4677],
        ...,
        [ 1.0175,  0.2681,  0.0362,  ...,  0.8128, -0.6224,  1.3235],
        [-1.1136,  1.1548, -0.3572,  ..., -1.2950, -1.5725, -0.0117],
        [-1.3484,  0.1052,  0.0677,  ..., -0.5857,  0.4291,  0.3004]],
       grad_fn=<ViewBackward0>)

In [19]:
b2.shape

torch.Size([1024])

In [20]:
b2.view(in_size,z_dim).shape

torch.Size([16, 64])